### ISSUE TITLE
How the fuck do i stop this

### ISSUE THREAD

**Issue by 6af** [foobball/EmailFlooder#2]
i tried this and it work now i cant stop outside online from texting me 24/7

**Comment by foobball** [comment]
no idea tbh

**Comment by iotalol** [comment]
@foobball please help i cant get rid of this shit either bro my data plan is accusing me of fruad and they are gonna sue me for all of my money because of the texts please i need help plz

**Comment by foobball** [comment]
you accepted the risks when using it on your number

**Comment by iotalol** [comment]
I didnt use it on my own phone ('6af') decided to do it too my phone.

**Comment by foobball** [comment]
> ahahaha this is the funniest shit

true

**Comment by 6af** [comment]
h
